
apiVersion: apps/v1
kind: Deployment
metadata:
  name: versions-app1
  namespace: simple-service  
spec:
  selector:
    matchLabels:
      app: versions-app
      ver: v1
  replicas: 5
  template:
    metadata:
      labels:
        app: versions-app
        ver: v1
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: application
        image: cloudstateu/versions-app:1
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: versions-app1
  namespace: simple-service
  labels:
    app: versions-app
    ver: v1
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: versions-app
    ver: v1
--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: versions-app2
  namespace: simple-service
spec:
  selector:
    matchLabels:
      app: versions-app
      ver: v2
  replicas: 5
  template:
    metadata:
      labels:
        app: versions-app
        ver: v2
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: application
        image: cloudstateu/versions-app:2
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: versions-app2
  namespace: simple-service
  labels:
    app: versions-app
    ver: v2
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: versions-app
    ver: v2
