
apiVersion: apps/v1
kind: Deployment
metadata:
  name: versions-app-error
  namespace: simple-service
spec:
  selector:
    matchLabels:
      app: versions-app
      ver: error
  replicas: 1
  template:
    metadata:
      labels:
        app: versions-app
        ver: error
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: application
        image: cloudstateu/versions-app:error
        ports:
        - containerPort: 5000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: versions-app-error
  namespace: simple-service
  labels:
    app: versions-app
    ver: error
spec:
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: versions-app
    ver: error
